project_id = "ebvcextapzrkzpowrxto"

[functions.upload-document]
verify_jwt = true

[functions.extract-runs]
verify_jwt = true

[functions.create-template]
verify_jwt = true

[functions.render-document]
verify_jwt = true

[functions.word-extract-runs]
verify_jwt = true

[functions.download-document]
verify_jwt = true

[functions.api-upload-document]
verify_jwt = false

[functions.analyze-document-fields]
verify_jwt = true

[functions.extract-openxml-runs]
verify_jwt = true

[functions.add-document-field]
verify_jwt = true

[functions.delete-document-field]
verify_jwt = true

[functions.update-document-field]
verify_jwt = true

[functions.extract-pdf-data]
verify_jwt = true
